---
- name: download a repository setup script
  become: yes
  get_url:
    url: https://rpm.nodesource.com/setup_{{ dist_version }}.x
    dest: /tmp/add_nodejs_repo.sh
    mode: 755
    force: yes

- name: adds a repository
  become: yes
  shell: /tmp/add_nodejs_repo.sh

- name: install a distribution
  become: yes
  yum:
    name: nodejs
    state: present
