---
- name: add haproxy service configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy.cfg
    owner: haproxy
    group: haproxy
    mode: 0700
    force: yes

- name: restart haproxy service
  service:
    name: haproxy
    state: restarted
