---
- name: add haproxy service configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    group: haproxy
    mode: 0644
    force: yes

- name: restart haproxy service
  service:
    name: haproxy
    enabled: yes
    state: restarted
