---
- name: create a functional user
  become: yes
  user:
    name: "{{ user_name }}"
    password: "{{ user_password_sha512_salted }}"
    createhome: yes
    home: "{{ home_dir }}"
    force: yes
    state: present

- name: create a distribution directory
  file:
    path: "{{ dist_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory

- name: download a distribution archive
  get_url:
    url: "{{ download_url }}"
    dest: "/tmp"

- name: unpack a distribution archive
  unarchive:
    src: "/tmp/{{ dist_archive }}"
    dest: "{{ dist_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    copy: no
    creates: "{{ dist_dir }}/{{ dist_name }}"

- name: rename distribution
  command: mv {{ dist_dir }}/{{ dist_name }} {{ dist_dir }}/{{ dist_version }}
  args:
    creates: "{{ dist_dir }}/{{ dist_version }}"

- name: create a distribution symlink
  file:
    path: "{{ dist_dir }}/default"
    src: "{{ dist_dir }}/{{ dist_version }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link

- name: create a nexus configuration
  template:
    src: nexus.properties.j2
    dest: "{{ dist_dir }}/default/conf/nexus.properties"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    force: yes

- name: create a nexus security configuration
  template:
    src: security.xml.j2
    dest: "{{ home_dir }}/conf/security.xml"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    force: yes

- name: create a java service wrapper config
  template:
    src: jsw/wrapper.conf.j2
    dest: "{{ dist_dir }}/default/bin/jsw/conf/wrapper.conf"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
    force: yes

- name: create a systemctl service script
  template:
    src: nexus.service.j2
    dest: /lib/systemd/system/nexus.service
    force: yes

- name: restart the service
  service:
    name: nexus
    enabled: yes
    state: restarted
