---
- name: create a functional user
  user:
    name: "{{ user_name }}"
    password: "{{ user_password_sha512_salted }}"
    createhome: yes
    home: "{{ user_home }}"
    state: present
    force: yes

- name: create a systemctl service config
  template:
    src: teamcity.j2
    dest: /etc/sysconfig/teamcity
    owner: root
    mode: 0644
    force: yes

- name: create a systemctl service script
  template:
    src: teamcity.service.j2
    dest: /lib/systemd/system/teamcity.service
    owner: root
    mode: 0644
    force: yes

- name: download a distribution archive
  become_user: "{{ user_name }}"
  get_url:
    url: "{{ dist_download_url }}"
    dest: "/tmp"
    force: no

- name: unpack a distribution archive
  unarchive:
    src: "tmp/{{ dist_archive }}"
    dest: "{{ user_home }}"
    owner: "{{ user_name }}"
    mode: 0644
    copy: no
    creates: "{{ dist_name }}"

- name: rename distribution
  become_user: "{{ user_name }}"
  command: mv {{ user_home }}/{{ dist_name }} {{ user_home }}/{{ dist_version }}
  args:
    creates: "{{ user_home }}/{{ dist_version }}"

- name: create a distribution symlink
  file:
    path: "{{ user_home }}/default"
    src: "{{ user_home }}/{{ dist_version }}"
    state: link
    owner: "{{ user_name }}"
    mode: 0644

- name: run a service
  service:
    name: teamcity
    state: running
