---
- name: create a systemctl service config
  become: yes
  template:
    src: teamcity.j2
    dest: /etc/sysconfig/teamcity
    force: yes

- name: create a systemctl service script
  become: yes
  template:
    src: teamcity.service.j2
    dest: /lib/systemd/system/teamcity.service
    force: yes

- name: create a functional user
  become: yes
  user:
    name: "{{ user_name }}"
    password: "{{ user_name }}"
    createhome: yes
    home: "{{ home_dir }}"
    state: present

- name: download a distribution archive
  become: yes
  become_user: "{{ user_name }}"
  get_url:
    url: "{{ download_url }}"
    dest: "{{ home_dir }}"

- name: unpack a distribution archive
  become: yes
  become_user: "{{ user_name }}"
  unarchive:
    src: "{{ home_dir }}/{{ dist_archive }}"
    dest: "{{ home_dir }}"
    copy: no
    creates: "{{ dist_name }}"

- name: rename distribution
  become: yes
  become_user: "{{ user_name }}"
  command: mv {{ home_dir }}/{{ dist_name }} {{ home_dir }}/{{ dist_version }}
  args:
    creates: "{{ home_dir }}/{{ dist_version }}"

- name: create a distribution symlink
  become: yes
  become_user: "{{ user_name }}"
  file: 
    path: "{{ home_dir }}/default"
    src: "{{ home_dir }}/{{ dist_version }}"
    state: link

- name: clean up
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ home_dir }}/{{ dist_archive }}"

- name: run a service
  become: yes
  service:
    name: teamcity
    state: running
