---
- name: change root password
  user:
    name: root
    password: "{{ user_password_sha512_salted }}"

- name: create a sshd service config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    force: yes

- name: create a functional user
  user:
    name: "{{ user_name }}"
    password: "{{ user_password_sha512_salted }}"
    createhome: yes
    home: "{{ user_home }}"
    state: present
    force: yes

- name: add the functional user to the sudoers list
  lineinfile:
    dest: /etc/sudoers
    line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
    state: present

- name: create ssh directory
  file:
      path: "{{ user_home }}/.ssh"
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: 0700

- name: add an authorized public key
  template:
    src: authorized_keys.j2
    dest: "{{ user_home }}/.ssh/authorized_keys"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0700
    force: yes

- name: restart sshd service
  service:
    name: sshd
    state: restarted


