---
- name: create a syslog config
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
    force: yes

- name: restart the syslog service
  service:
    name: rsyslog
    state: restarted

