---
- set_fact:
    seed_nodes: "{{ [play_hosts[0]] if play_hosts|length == 1 else [play_hosts[0], play_hosts[1]] }}"
    create_keyspaces_query: "{{ lookup('file', role_path + '/files/create-keyspaces.cql') }}"

- name: add the datastax repository config
  become: yes
  template:
    src: datastax.repo.j2
    dest: /etc/yum.repos.d/datastax.repo
    force: yes

- name: install cassandra
  become: yes
  yum:
    name: dsc{{ dist_version }}
    state: present

- name: install cassandra tools
  become: yes
  yum:
    name: cassandra{{ dist_version }}-tools
    state: present

- name: add the cassandra config
  become: yes
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/conf/cassandra.yaml
    force: yes

- name: start cassandra
  become: yes
  service:
    name: cassandra
    enabled: yes
    state: restarted

- name: wait for cassandra to start
  wait_for:
    port: "{{ native_transport_port }}"
    delay: 20
    state: started

- name: create a temporary scripts directory
  run_once: yes
  become: yes
  file:
    path: "{{ tmp_scripts_dir }}"
    state: directory

- name: copy create keyspaces script
  run_once: yes
  become: yes
  copy:
    src: "{{ role_path }}/files/{{ create_keyspaces_script }}"
    dest: "{{ tmp_scripts_dir }}/{{ create_keyspaces_script }}"
    force: yes

- name: run create keyspaces script
  run_once: yes
  command: cqlsh -f {{ tmp_scripts_dir }}/{{ create_keyspaces_script }}

- name: copy create tables script
  run_once: yes
  become: yes
  copy:
    src: "{{ role_path }}/files/{{ create_tables_script }}"
    dest: "{{ tmp_scripts_dir }}/{{ create_tables_script }}"
    force: yes

- name: run create tables script
  run_once: yes
  command: cqlsh -f {{ tmp_scripts_dir }}/{{ create_tables_script }}

- name: remove the temporary scripts directory
  run_once: yes
  become: yes
  file:
    path: "{{ tmp_scripts_dir }}"
    state: absent
