---
- name: reload the server service
  command: systemctl daemon-reload

- name: restart the server service
  service:
    name: website
    enabled: yes
    state: restarted

- name: wait for the server service
  wait_for:
    port: "{{ server_http_port }}"
    delay: 10
    timeout: 60
    state: started

